<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="2" ignored="0" total="10" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="31801" started-at="2021-10-30T12:09:20Z" finished-at="2021-10-30T12:09:52Z">
    <groups>
      <group name="Ramesh">
        <method signature="Test2.DashboardUserText()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="DashboardUserText" class="com.testCases.Test2"/>
        <method signature="Test2.listOfCourses()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="listOfCourses" class="com.testCases.Test2"/>
        <method signature="Test2.DashboardUserText()[pri:0, instance:com.testCases.Test2@158da8e]" name="DashboardUserText" class="com.testCases.Test2"/>
        <method signature="Test2.listOfCourses()[pri:0, instance:com.testCases.Test2@158da8e]" name="listOfCourses" class="com.testCases.Test2"/>
      </group> <!-- Ramesh -->
      <group name="Rohan">
        <method signature="Test2.loginTest()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="loginTest" class="com.testCases.Test2"/>
        <method signature="Test2.Dashboard()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="Dashboard" class="com.testCases.Test2"/>
        <method signature="Test2.loginTest()[pri:0, instance:com.testCases.Test2@158da8e]" name="loginTest" class="com.testCases.Test2"/>
        <method signature="Test2.Dashboard()[pri:0, instance:com.testCases.Test2@158da8e]" name="Dashboard" class="com.testCases.Test2"/>
      </group> <!-- Rohan -->
    </groups>
    <test name="Test1" duration-ms="20578" started-at="2021-10-30T12:09:20Z" finished-at="2021-10-30T12:09:41Z">
      <class name="com.testCases.Test2">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.testCases.Test2@20ce78ec]" name="setup" is-config="true" duration-ms="10600" started-at="2021-10-30T12:09:20Z" finished-at="2021-10-30T12:09:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="DashboardUserText()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="DashboardUserText" duration-ms="6492" started-at="2021-10-30T12:09:31Z" description="User" finished-at="2021-10-30T12:09:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DashboardUserText -->
        <test-method status="PASS" signature="listOfCourses()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="listOfCourses" duration-ms="1109" started-at="2021-10-30T12:09:38Z" description="list" finished-at="2021-10-30T12:09:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listOfCourses -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="loginTest" duration-ms="430" depends-on-groups="Ramesh" started-at="2021-10-30T12:09:39Z" description="Login" finished-at="2021-10-30T12:09:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="SKIP" signature="Dashboard()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="Dashboard" duration-ms="631" started-at="2021-10-30T12:09:39Z" description="Dash" depends-on-methods="com.testCases.Test2.loginTest" finished-at="2021-10-30T12:09:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<JavaByKiran | Dashboard> but was:<JavaByKiran | Dashboard1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<JavaByKiran | Dashboard> but was:<JavaByKiran | Dashboard1>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at com.testCases.Test2.Dashboard(Test2.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dashboard -->
        <test-method status="SKIP" signature="Dashboard()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="Dashboard" duration-ms="646" started-at="2021-10-30T12:09:40Z" description="Dash" depends-on-methods="com.testCases.Test2.loginTest" finished-at="2021-10-30T12:09:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<JavaByKiran | Dashboard> but was:<JavaByKiran | Dashboard1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<JavaByKiran | Dashboard> but was:<JavaByKiran | Dashboard1>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at com.testCases.Test2.Dashboard(Test2.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dashboard -->
        <test-method status="FAIL" signature="Dashboard()[pri:0, instance:com.testCases.Test2@20ce78ec]" name="Dashboard" duration-ms="573" started-at="2021-10-30T12:09:40Z" description="Dash" depends-on-methods="com.testCases.Test2.loginTest" finished-at="2021-10-30T12:09:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<JavaByKiran | Dashboard> but was:<JavaByKiran | Dashboard1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<JavaByKiran | Dashboard> but was:<JavaByKiran | Dashboard1>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at com.testCases.Test2.Dashboard(Test2.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dashboard -->
      </class> <!-- com.testCases.Test2 -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="11154" started-at="2021-10-30T12:09:41Z" finished-at="2021-10-30T12:09:52Z">
      <class name="com.testCases.Test2">
        <test-method status="PASS" signature="setup(java.lang.String)[pri:0, instance:com.testCases.Test2@158da8e]" name="setup" is-config="true" duration-ms="2691" started-at="2021-10-30T12:09:41Z" finished-at="2021-10-30T12:09:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="DashboardUserText()[pri:0, instance:com.testCases.Test2@158da8e]" name="DashboardUserText" duration-ms="5015" started-at="2021-10-30T12:09:44Z" description="User" finished-at="2021-10-30T12:09:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DashboardUserText -->
        <test-method status="PASS" signature="listOfCourses()[pri:0, instance:com.testCases.Test2@158da8e]" name="listOfCourses" duration-ms="1681" started-at="2021-10-30T12:09:49Z" description="list" finished-at="2021-10-30T12:09:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listOfCourses -->
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.testCases.Test2@158da8e]" name="loginTest" duration-ms="325" depends-on-groups="Ramesh" started-at="2021-10-30T12:09:51Z" description="Login" finished-at="2021-10-30T12:09:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="FAIL" signature="Dashboard()[pri:0, instance:com.testCases.Test2@158da8e]" name="Dashboard" duration-ms="1386" started-at="2021-10-30T12:09:51Z" description="Dash" depends-on-methods="com.testCases.Test2.loginTest" finished-at="2021-10-30T12:09:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<JavaByKiran | Dashboard> but was:<JavaByKiran | Dashboard1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<JavaByKiran | Dashboard> but was:<JavaByKiran | Dashboard1>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
at com.testCases.Test2.Dashboard(Test2.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Dashboard -->
      </class> <!-- com.testCases.Test2 -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
